# Generated by Django 2.2.8 on 2026-02-17 14:25

import account.managers
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(blank=True, default='user', help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, verbose_name='fullname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number')),
                ('job_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Job Title')),
                ('timezone', models.CharField(choices=[('Pacific/Kwajalein', '(GMT -12:00) Eniwetok, Kwajalein'), ('Pacific/Samoa', '(GMT -11:00) Midway Island, Samoa'), ('Pacific/Honolulu', '(GMT -10:00) Hawaii'), ('America/Anchorage', '(GMT -9:00) Alaska'), ('America/Los_Angeles', '(GMT -8:00) Pacific Time (US, Canada)'), ('America/Denver', '(GMT -7:00) Mountain Time (US, Canada)'), ('America/Chicago', '(GMT -6:00) Central Time (US, Canada), Mexico City'), ('America/New_York', '(GMT -5:00) Eastern Time (US, Canada), Bogota, Lima'), ('America/Glace_Bay', '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz'), ('America/St_Johns', '(GMT -3:30) Newfoundland'), ('America/Buenos_Aires', '(GMT -3:00) Brazil, Buenos Aires, Georgetown'), ('America/Noronha', '(GMT -2:00) Mid-Atlantic'), ('Atlantic/Azores', '(GMT -1:00 hour) Azores, Cape Verde Islands'), ('Europe/London', '(GMT) Western Europe Time, Dublin, London, Lisbon, Casablanca'), ('Europe/Madrid', '(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris'), ('Europe/Minsk', '(GMT +2:00) Kaliningrad, South Africa'), ('Europe/Moscow', '(GMT +3:00) İstanbul, Ankara, Riyadh, Moscow'), ('Asia/Tehran', '(GMT +3:30) Tehran'), ('Asia/Dubai', '(GMT +4:00) Abu Dhabi, Dubai, Baku, Tbilisi'), ('Asia/Kabul', '(GMT +4:30) Kabul'), ('Asia/Tashkent', '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent'), ('Asia/Kolkata', '(GMT +5:30) Bombay, Chennai, Mumbai, New Delhi'), ('Asia/Katmandu', '(GMT +5:45) Kathmandu'), ('Asia/Almaty', '(GMT +6:00) Astana, Almaty, Dhaka, Colombo'), ('Asia/Bangkok', '(GMT +7:00) Bangkok, Hanoi, Jakarta'), ('Asia/Singapore', '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong'), ('Asia/Tokyo', '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk'), ('Australia/Darwin', '(GMT +9:30) Adelaide, Darwin'), ('Australia/Melbourne', '(GMT +10:00) Eastern Australia, Guam, Vladivostok'), ('Pacific/Ponape', '(GMT +11:00) Magadan, Solomon Islands, New Caledonia'), ('Pacific/Auckland', '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka')], default='Asia/Dubai', max_length=100, verbose_name='Timezone')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_image', verbose_name='Picture')),
                ('day_of_week', models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1, verbose_name='First day of week')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_master', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            managers=[
                ('objects', account.managers.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(null=True, upload_to='media//company', verbose_name='Logo')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector')),
                ('timezone', models.CharField(choices=[('Pacific/Kwajalein', '(GMT -12:00) Eniwetok, Kwajalein'), ('Pacific/Samoa', '(GMT -11:00) Midway Island, Samoa'), ('Pacific/Honolulu', '(GMT -10:00) Hawaii'), ('America/Anchorage', '(GMT -9:00) Alaska'), ('America/Los_Angeles', '(GMT -8:00) Pacific Time (US, Canada)'), ('America/Denver', '(GMT -7:00) Mountain Time (US, Canada)'), ('America/Chicago', '(GMT -6:00) Central Time (US, Canada), Mexico City'), ('America/New_York', '(GMT -5:00) Eastern Time (US, Canada), Bogota, Lima'), ('America/Glace_Bay', '(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz'), ('America/St_Johns', '(GMT -3:30) Newfoundland'), ('America/Buenos_Aires', '(GMT -3:00) Brazil, Buenos Aires, Georgetown'), ('America/Noronha', '(GMT -2:00) Mid-Atlantic'), ('Atlantic/Azores', '(GMT -1:00 hour) Azores, Cape Verde Islands'), ('Europe/London', '(GMT) Western Europe Time, Dublin, London, Lisbon, Casablanca'), ('Europe/Madrid', '(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris'), ('Europe/Minsk', '(GMT +2:00) Kaliningrad, South Africa'), ('Europe/Moscow', '(GMT +3:00) İstanbul, Ankara, Riyadh, Moscow'), ('Asia/Tehran', '(GMT +3:30) Tehran'), ('Asia/Dubai', '(GMT +4:00) Abu Dhabi, Dubai, Baku, Tbilisi'), ('Asia/Kabul', '(GMT +4:30) Kabul'), ('Asia/Tashkent', '(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent'), ('Asia/Kolkata', '(GMT +5:30) Bombay, Chennai, Mumbai, New Delhi'), ('Asia/Katmandu', '(GMT +5:45) Kathmandu'), ('Asia/Almaty', '(GMT +6:00) Astana, Almaty, Dhaka, Colombo'), ('Asia/Bangkok', '(GMT +7:00) Bangkok, Hanoi, Jakarta'), ('Asia/Singapore', '(GMT +8:00) Beijing, Perth, Singapore, Hong Kong'), ('Asia/Tokyo', '(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk'), ('Australia/Darwin', '(GMT +9:30) Adelaide, Darwin'), ('Australia/Melbourne', '(GMT +10:00) Eastern Australia, Guam, Vladivostok'), ('Pacific/Ponape', '(GMT +11:00) Magadan, Solomon Islands, New Caledonia'), ('Pacific/Auckland', '(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka')], default='Asia/Dubai', max_length=100, verbose_name='Timezone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
                ('role', models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(null=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
