# Generated by Django 2.2.8 on 2026-02-17 14:26

import django.db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20260217_1425'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', django.db.models.JSONField(default=dict, verbose_name='Extra Data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
