# Generated by Django 2.2.8 on 2026-02-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
        ('core', '0002_devicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='display.Display'),
        ),
    ]
