
services:
    postgres-new:
        container_name: postgres-new
        image: postgres:16
        restart: always
        volumes:
            - ./pgdb/:/var/lib/postgresql/data/
        ports:
            - "5433:5432"
        env_file: .env
        networks:
            - internal
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s


    web:
        container_name: dsqmeter-new
        build: .
        restart: "always"
        command: ["supervisord", "-c", "/code/supervisord.conf"]
        environment:
            - VIRTUAL_HOST=qmeterds.kapitalbank.az,10.0.4.132,localhost
            - VIRTUAL_PROTO=http
            - CERT_NAME=kapitalbank_az
            - VIRTUAL_PORT=8000
            - TIMEOUT=300
            - HTTP_PORT=8000
            - STATS_PORT=8001
            - LANG=en_US.UTF-8
            - LANGUAGE=en_US:en
            - LC_ALL=en_US.UTF-8
        ports:
            - "8002:8000"
        volumes:
            - .:/code/
            - ./static/:/code/static
            - ./media/:/code/media
        networks:
            - internal
            - nginx-proxy
        depends_on:
            postgres-new:
                condition: service_healthy
        env_file: .env

networks:
    internal:
        driver: bridge
    nginx-proxy:
        external: true