[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:uwsgi]
command=uwsgi --ini /code/uwsgi.ini
directory=/code
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:checker]
command=python manage.py check_device_status
directory=/code
autostart=true
autorestart=true
startretries=999
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
