# Generated by Django 2.2.8 on 2026-02-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist', '0001_initial'),
        ('account', '0002_auto_20260217_1425'),
        ('display', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaygroup',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist'),
        ),
        migrations.AddField(
            model_name='displaygroup',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.Schedule'),
        ),
        migrations.AddField(
            model_name='display',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch.Branch'),
        ),
        migrations.AddField(
            model_name='display',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company'),
        ),
        migrations.AddField(
            model_name='display',
            name='display_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='display.DisplayGroup'),
        ),
        migrations.AddField(
            model_name='display',
            name='display_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.DisplayType'),
        ),
        migrations.AddField(
            model_name='display',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist'),
        ),
        migrations.AddField(
            model_name='display',
            name='schedule',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.Schedule'),
        ),
    ]
