# Generated by Django 2.2.8 on 2026-02-17 14:26

import django.db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('display', '0001_initial'),
        ('account', '0002_auto_20260217_1425'),
        ('core', '0003_devicelog_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('extra_fields', django.db.models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
                ('default_display_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.DisplayType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
                ('default_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Duration')),
                ('bg_color', models.CharField(max_length=100, verbose_name='Background color')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Company')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlideItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top', models.PositiveIntegerField(default=0, verbose_name='Top')),
                ('left', models.PositiveIntegerField(default=0, verbose_name='Left')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Width')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Height')),
                ('index', models.PositiveIntegerField(default=0, verbose_name='Index')),
                ('attr', django.db.models.JSONField(default=dict, verbose_name='Attr')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Slide')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_type', to='core.WidgetType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SlideItemDisplayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top', models.PositiveIntegerField(default=0, verbose_name='Top')),
                ('left', models.PositiveIntegerField(default=0, verbose_name='Left')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Width')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='Height')),
                ('display_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.DisplayType')),
                ('slide_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.SlideItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('repeat', models.BooleanField(default=False, verbose_name='Repeat')),
                ('repeat_type', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=100, null=True, verbose_name='Repeat Type')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Is all day')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Schedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
