services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.serve
    container_name: ds-front
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=10.0.4.132
      - VIRTUAL_PORT=3333
      - PORT=3333
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    ports:
      - 3333:3333

networks:
  default:
    name: nginx-proxy
    external: true
