services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.fullbuild
    container_name: ds-front-new
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=qmeterds.kapitalbank.az,10.0.4.132
      - VIRTUAL_PORT=3334
      - PORT=3334
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    ports:
      - 3334:3334

networks:
  default:
    name: nginx-proxy
    external: true
